version: '3'
services:
  db-mysql:
    image: "mysql:5.7"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=tax
    volumes:
      - my-datavolume:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: dev
    restart: 'always'
    ports:
      - 8001:8001
    depends_on:
      - db-mysql
    links:
      - db-mysql
    environment:
      - NODE_ENV=development
      - MYSQL_DATABASE=tax
volumes:
  my-datavolume:
